version: '2'
services:
  mariadb:
    image: mariadb
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=db-user
    - MYSQL_PASSWORD=pw
    - MYSQL_ROOT_PASSWORD=root-pw
#    volumes:
#    - mysql-data:/var/lib/mysql
#    - ./mysql_config:/etc/mysql
    restart: always