name: build gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Execute Gradle task
      uses: MrRamych/gradle-actions/openjdk-8@3.1
      with:
        args: test
